spring.application.name=finance_dashboard_system
spring.datasource.url=jhv,jhb,jhb,jhbddfkna
spring.datasource.username=jhb,jhbvdfvsvsdv
spring.datasource.password=jhjxbcvkjzxnk.dvjnx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
